### ISSUE TITLE
Is geneflow restricted to overlapping region for populations with incomplete overlap?

### ISSUE THREAD

**Issue by jahink17** [bodkan/slendr#103]
Hi @bodkan, I'm working with @mmosmond on modelling some _A. Thaliana_ populations and we've been trying to figure out the best way to approach coding up an "admixture" scenario in slendr. We were hoping you could help shed some light on it.

We have an ancestral population that starts out in central Africa and then expands throughout Africa, before splitting up into two subpopulations in Morocco and in the Middle East. At this point, the two subpopulations are completely distinct, and have no gene flow between them. We then have a westward expansion of the Middle Eastern population towards Morocco, culminating in admixture with the Moroccan population in Spain. The last part is what we're having trouble with - what we want is for there to be intermixing between the two populations at some given rate only in the region where they overlap.

We thought of implementing this by setting geneflow rates of, e.g., 0.5 from the mideastern pop to the moroccan pop and another one going the opposite way (also 0.5), but we're not sure about what exactly this `gene_flow()` function would do under the hood. We’re specifically worried that some children produced in the non-overlapping region will become part of the other population, affecting genetic variation in a way we don’t want. We understand that, with `overlap=True` in the `gene_flow()` function callback, overlap between the subpopulations is necessary for geneflow to occur. We were just looking for some clarification on how `gene_flow()` works when `overlap=True` and there is some (but not complete) overlap between the subpopulations i.e. which offspring are chosen to be migrants.

Looking into this a bit more, when `overlap=True` (as is the case with our implementation), the `modifyChild()` callback seems to ensure that every child produced is: 1. within the dispersal kernel of one of the parents (which would be from the e.g., Moroccan subpopulation) and 2. within the spatial bounds of the population it’s currently in (e.g., the Middle Eastern subpopulation if the child is a migrant). The code first implements (1), choosing a location for the child according to the parent’s coordinates and the dispersal kernel,  and then checks if (2) is satisfied. If it isn’t, a different location is chosen until a certain maximum number of attempts have taken place, after which, if a suitable location has not been found, the child is discarded. To us, it seems like this would ensure that admixture is restricted to the overlapping region (and no unwanted effects in the non-overlapping region), and so simply setting a bidirectional geneflow rate of 0.5 between the two subpopulations should be sufficient to get what we wanted.

Is this right? We just wanted to clarify because it seems like admixture events will be a common thing to model and we didn’t find examples or clarification in the tutorials. Thanks for making this great software!

**Comment by bodkan** [comment]
Hello @jahink17! Thank you for your interest in slendr. I'm a big fan of the work you guys have been doing in terms of spatio-temporal inference. In fact, this entire project's origin has been motivated in large part by that work!

I have been unfortunately super swamped this week (as you could probably tell by the delay in answering). Next week I'm teaching at a course and hope to have a bit more breathing space. I will reply early next week! Thanks for your patience.

**Comment by bodkan** [comment]
Hello, sorry for the delay! Things at work have been getting out of control and slendr support has been suffering as a result...

I feel a bit bad about having you wait so long because I think the answer to your message is very simple.

> what we want is for there to be intermixing between the two populations at some given rate only in the region where they overlap
> [...]
> it seems like this would ensure that admixture is restricted to the overlapping region (and no unwanted effects in the non-overlapping region), and so simply setting a bidirectional geneflow rate of 0.5 between the two subpopulations should be sufficient to get what we wanted.

Yes, this is exactly how admixture is implemented in the SLiM back end under the hood. For spatial simulations, if overlap = TRUE, the admixture only occurs in the region of overlap between the two populations. 

I hope I understood your question correctly. If what I quoted and responded to is not everything you wondered about, please let me know!

I'm sorry that the tutorials or documentation have not made it clear enough! I admit the docs are more than barebones in some places...

**Comment by jahink17** [comment]
Hi, no worries about the delay! That did answer our question perfectly. Thank you for the clarification and, once again, for making this great software! It's proved to be extremely useful for our project.

**Comment by bodkan** [comment]
Glad to hear that! Can’t wait to see how you put slendr to use in your project.

Just a heads up: in case you missed it, there have been some important [updates](https://github.com/bodkan/slendr/blob/main/NEWS.md) to slendr recently as part of the CRAN submission. Nothing earth-shattering but still, good to be aware of this in case you update at some point. 

Good luck and don’t hesitate to get in touch if you run into issues!
