### ISSUE TITLE
Add SLiM's selfing rate function to slendR?

### ISSUE THREAD

**Issue by ornobalam** [bodkan/slendr#109]
Hi Martin,

We briefly talked about this during the Copenhagen workshop. Here is how I am adding selfing after running the slim() function with method = "gui":

function (void) create_pop(object<Dictionary> pop) {
    pop_id = pop.getValue("pop_id");

    if (pop.getValue("parent") ==  "ancestor") {
        log_output("creating " + pop.getValue("pop") + "(p" + pop.getValue("pop_id") + ")");
        sim.addSubpop(pop_id, pop.getValue("N"));
        **get_pop(pop_id).setSelfingRate(0.96);**
    } else {
        log_output(
            "split of " + pop.getValue("pop") + "(p" + pop.getValue("pop_id") + ")" +
            " from " + pop.getValue("parent") + "(p" + pop.getValue("parent_id")  + ")"
        );
        sim.addSubpopSplit(pop_id, pop.getValue("N"), pop.getValue("parent_id"));
        **get_pop(pop_id).setSelfingRate(0.96);**

    }

This is adding selfing globally to all populations when they're created. We discussed possibly adding an argument inside the population() function to set the selfing rate for each population.

Best,
Ornob

**Comment by bodkan** [comment]
Thank you for the suggestion, Ornob! This will be very easy to do. I'll post an update once I get to it.

It was very nice meeting you!

**Comment by ornobalam** [comment]
Thank you so much! I am glad this will be simple. It was great talking to
you!

Ornob
