### ISSUE TITLE
slim binary not found

### ISSUE THREAD

**Issue by jielab** [bodkan/slendr#124]
Hi, there:

When i try to run the example code for Figure 3 of your paper, I got an "slim binary not found" error.

Can you please let me know how to fix this?

Thank you veyr much!

best regadrs,
Jie

**Comment by bodkan** [comment]
Do you have SLiM installed?

What happens when you call `library(slendr)` in a fresh new R session? Does it write anything about SLiM being present on your system and found?

**Comment by jielab** [comment]
Dear Petr: 

thanks for your reply. please see the screenshot below. it seems that slim is not installed or not in the PATH. I know how to find things and add path in Linux, but not sure how to do this on Windows. Is slim a R package like slendr, or is it a python package that i should install it with pip/conda install?

Thank you & best regards,
Jie

![image](https://user-images.githubusercontent.com/26947455/222914040-d5fcfa56-71e7-4fcf-9ccf-3d1094eb3c71.png)

**Comment by bodkan** [comment]
Hello Jie,

I have bad news -- although slendr's coalescent (msprime) back end and tskit-based tree sequence functionality have been ported to Windows last year, there is currently no way to run slendr with SLiM on Windows :(

[SLiM](https://messerlab.org/slim/) is a forwards time population genetic simulator which slendr internally used for all spatial simulations (such as the code in Figure 3 of my paper). SLiM does work on Windows without issues but I haven't had any chance to figure out how to port this functionality of slendr to Windows.

To be honest, I don't think it would be difficult to do -- I'd have to figure out how a `$PATH` equivalent operates on Windows, and make some changes to how slendr looks for output files but I have no access to a Windows computer to develop this and test it.

I hope to take a look at it at some point soon by borrowing some Windows machine at work for a couple of afternoons but until then, there is no way to run SLiM-based spatial simulations with slendr on Windows. Sorry.

---

I know there is something called [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/install) which apparently allows one to run full Linux environment under Windows. This would allow you to run everything in slendr as it is now, on Windows. Unfortunately, I have no practical experience with this.

**Comment by jielab** [comment]
Thanks, Petr!

I actually have "Windows Subsystem for Linux" and I could run R from there. That is not a problem at all.
Usually when I hear that something runs on R, I automatically open the Windows R without thinking of Linux :- )

For Figure 5B of your paper, what does those numbers (25, 18, etc.) and the colors (25 in red, 10 in green) mean? I guess it is not "25 generations", because a EUR person separated from an YAM person certainly much longer than that. 

Also, how could the same person ("EUR_578") shows up twice in a phylogeny and also have two different evolutionary path as shown in Figure 5D?  Is this type of analysis and visualization more or less like that one would get from ancestry.com?

Finally, I am still confused about Figure 5C after reading the figure legend. First, is that for a single person such as that in Figure 5D? Second, why some boxes have a single number and other boxes have two numbers?

Thank you very much!

Best regards,
Jie

**Comment by bodkan** [comment]
Happy to answer your questions about my paper, but let’s do it over email as they’re not related to your original issue.

Closing this.

**Comment by jielab** [comment]
Dear Petr:

 

Yes, sure. Can you please kindly let me know your email address then?

 

Mine is ***@***.*** ***@***.***> 

 

Thank you & best regards,

Jie

 

 

发件人: Martin Petr ***@***.***> 
发送时间: 2023年3月5日 3:34
收件人: bodkan/slendr ***@***.***>
抄送: Jie Huang ***@***.***>; Author ***@***.***>
主题: Re: [bodkan/slendr] slim binary not found (Issue #124)

 

Happy to answer your questions about my paper, but let’s do it over email as they’re not related to your original issue.

Closing this.

**Comment by jielab** [comment]
Dear Petr:

I now encountered the following error when trying to install the slendr R package into the Linux system.

![image](https://user-images.githubusercontent.com/26947455/222934887-302b06e6-6e9e-4ed0-8096-f09e8f763b5b.png)

My email is jiehuang001 at gmail dot com.  Please kindly shot me an email as I do have a couple of more questions/suggestions for the general functionality for slendr.

Best regards,
jie

**Comment by bodkan** [comment]
Sorry, don't know what this could mean.

I suggest you scroll through the _entire_ installation log. The R installation process always tells you if there are potentially some C/C++ library headers missing. The screenshot suggests that "sf", "stars", "rnaturalearth", "ijtiff" R packages could not be installed. You might want to start by installing them first, one by one, and seeing what went wrong.

(My name is Martin, BTW.)

**Comment by bodkan** [comment]
Also, if you're still struggling, open an appropriate issue with the right title. This creates a bit of a mess when I (or other users) search for previously solved problems.

Your current problem is not related to "slim binary not found".
