### ISSUE TITLE
A fundamental design question for Slendr

### ISSUE THREAD

**Issue by jielab** [bodkan/slendr#126]
Dear Martin:

I found that the plots on your paper is very attrative, but I am still having difficulty to understand exactly what it intends to achieve. 

Based on Figure 1 of your paper. Below is the INPUT and OUTPUT of the program, correct?
1. the INPUT is "defining the world" and "creating populations" and "demographic events";
2. the Engine is "model compilation" and "schedule sampling" and "Simulation";
3. the OUTPUT is some tree sequence files (i.e., phylogeny).

Now, take your "Figure 5. Example 4" for example. Figure 5C and 5D are part of the INPUT data, and Figure 5B is the OUTPUT, correct?
If so, it would be better to put 5B after 5C-D. As I previously asked, how could one same person shows up twice in Figure 5B, if Figure 5B is a phylogeny plot?

Don't know if you have read this 2022 Science paper, **A unified genealogy of modern and ancient genomes** (https://www.science.org/doi/10.1126/science.abi8264). It uses real genetic data to infer a tree sequence of individuals. But it seems to me that slendr does not use any real genetic data. Do you see a good way to make slendr compatible or complimentary to this unified genealogy?

Best regadrs,
Jie

**Comment by bodkan** [comment]
I'm sorry but this sort of discussion really doesn't belong on GitHub. This place is for reporting and discussion of bugs and feature requests for slendr software.

As I said elsewhere under another of issues, please send your general questions, doubts, etc. on my email. You can find the contact info on [my website](https://www.bodkan.net).

Apologies, but I will close this issue as well. Staying on top of bugs, fixes and other software-related issues is already a lot of work and having general discussions in here would be too distracting. Thanks for understanding.

**Comment by bodkan** [comment]
Hold on, I see in my inbox an email from you regarding the Wohns et al paper from a week ago? So it seems you do have my email address. I know I have not replied yet (life has been very busy recently) but why not send your questions as a follow up to that email. Elsewhere here on Github you had other questions about figures from my paper  and about the Wohns at al paper -- please send those as a follow up to that email as well.
