### ISSUE TITLE
Figure out a more convenient way to coalesce lineages in `ts_recapitate`

### ISSUE THREAD

**Issue by bodkan** [bodkan/slendr#67]
I had to add an emergency implementation of [migration matrix](https://pyslim.readthedocs.io/en/latest/python_api.html#pyslim.SlimTreeSequence.recapitate) for recapitation for an internal project. However, the Python way of specifying list-of-lists is supremely unidiomatic for R and also very inconvenient compared to other _slendr_ interfaces which are much easier to use. There must be a more elegant way to do this which would leverage proper population names.

**Comment by petrelharp** [comment]
Is this issue still pending? I have suggestions, if so.

**Comment by bhaller** [comment]
Note that in SLiM 3.7 (and in GitHub now) subpopulations can be given a `name` property, which is persisted in the population table in the tree sequence as metadata.  So you should be able to refer to population names symbolically on the Python side.

**Comment by bodkan** [comment]
@petrelharp: Yes, still pending. I had no time to think about it and would love to hear your thoughts.

@bhaller: This is great to hear! Thanks for letting me now about this. You're right, this should make it very easy to solve this. I will take a look at the appropriate slendr/pyslim/tskit/msprime/reticulate plumbing.

More generally, this is yet another feature that will significantly simplify the SLiM backend code, retiring [this](https://github.com/bodkan/slendr/blob/be92b58bb013bfbdd96f1b81a3d613124d9e242c/inst/extdata/script.slim#L550) little helper function. 🙂 I will add this to my notes on the SLiM 3.7 transition which I'll deal with in one fell swoop in a single PR when SLiM 3.7 is out. Whenever that happens--I'm still in no rush with regards to that.

**Comment by bhaller** [comment]
> Whenever that happens--I'm still in no rush with regards to that.

You may not be in a rush, but I am.  :->  It will be released before I go on vacation December 19th, if there is any way I can possibly make that happen.  :->
