### ISSUE TITLE
The slim binary was not found in your $PATH variable. 

### ISSUE THREAD

**Issue by jaurbanChicago** [bodkan/slendr#75]
Hello, 
I keep getting this error prompt everytime I install slendr on my RStudio:

`The slim binary was not found in your $PATH variable. Most of
the functionality in this package will work without any issues
but you will not be able to simulate data with the `slim()` function.`

I have been able to run every command from the tutorial, except the SLiM one where I get this error prompt:

`Error: slim binary not found. Please modify your $PATH accordingly or                         
specify the path manually by setting the 'binary_path' argument.`

Is there any way I can fix this problem? How is the $PATH modified?

Thanks in advance

**Comment by thesnakeguy** [comment]
@jaurbanChicago How did you eventually solve this issue? Many thanks.

**Comment by bodkan** [comment]
Hi there, 

are you on Mac or Linux?

Do you have SLiM installed on your system?

**Comment by bodkan** [comment]
Hey Pablo, thanks for getting back to me.

Sorry for the Windows trouble. As noted elsewhere, it appears that the [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/install) is a reasonably convenient way to run unix software on Windows. For the time being, maybe this will work?

In any case, keep an eye on [this](https://github.com/bodkan/slendr/issues/125) issue. You can even subscribe there to get an email notification as soon as there is an update.

Given that there are two confirmed people interested in porting the SLiM bits of _slendr_ to Windows, I have finally the motivation to do this. :)

Thank you for your patience!
