### ISSUE TITLE
Question about Sampling Process

### ISSUE THREAD

**Issue by jaurbanChicago** [bodkan/slendr#81]
Hello Martin,

I have a question about the slendr sampling process. I am interested in sampling individuals of three different time slices from within single locations in Europe. I am attaching a map to show you what I would like to do:
![Europe_Sampling_Places](https://user-images.githubusercontent.com/90297093/154337773-73cd6cf4-0fd2-4010-bf0f-a09bb1d01ca5.png)

As you can see, I want individuals to come from a single location (simulating a small town/village across time). However, the individuals sampled for your tutorial vignettes are scattered across the map: 

![map_Europe_Samplings_tutorial](https://user-images.githubusercontent.com/90297093/154338263-5537e4b9-2729-4a74-97ae-364f1d88a59d.png)

I guess the model would need to be changed maybe??? I used the model shown in this tutorial https://www.slendr.net/articles/vignette-06-locations.html#scheduling-sampling-events-and-simulation.

Thank you so much in advance. 

Best, 

Toño

**Comment by bodkan** [comment]
Hello again Toño,

First of all, I have to say I'm beyond excited you're already simulating real spatial data! I can't wait to see what you guys are doing and what kinds of projects in general will slendr allow people to do. I'm just about done with the manuscript dedicated to the software and this is a great motivation to push forward.

To your question: I have recently implemented a feature which should hopefully help you do exactly this.

Take a look at the manual page of the [`sampling()` function](https://www.slendr.net/reference/sampling.html). You will note there is an optional argument `locations = ` which allows you to specify _where_ should given number of individuals from given populations be sampled.

(Un)fortunately, the stream of new features over the last 3-4 months has been too significant and things have been moving too quickly to update all vignettes to showcase the usage of all of them.

That said, maybe this bit of code in slendr's [unit tests](https://github.com/bodkan/slendr/blob/main/tests/testthat/test-sampling.R#L69) will help? In particular, in the linked unit test script, you will note that the `locations = ` argument can be of the form such as

`sampling(model, times = ..., locations = list(c(10, 15), c(0, 30), list(popA, 5), list(popB, 5), ...)`

etc, indicating that 5 individuals from _popA_ and _popB_ should be sampled at given time points as close to locations [10, 15] and [0, 30] (degrees lon/lat, for instance) as possible.

Hope this helps!

**Comment by jaurbanChicago** [comment]
Hello again Martin, 

Is there a problem with the downloading process of the slendr package? I tried to download the newest version and this error prompt came out:

`> devtools::install_github("bodkan/slendr")
Downloading GitHub repo bodkan/slendr@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/bodkan/slendr/tarball/HEAD' failed`

**Comment by jaurbanChicago** [comment]
```
The downloaded binary packages are in
	/var/folders/v0/h1l93y5d56ndrcl7bg26gysc0000gn/T//RtmpITV464/downloaded_packages
✓  checking for file ‘/private/var/folders/v0/h1l93y5d56ndrcl7bg26gysc0000gn/T/RtmpITV464/remotesac6781648bc/bodkan-slendr-a99e00c/DESCRIPTION’ (439ms)
─  preparing ‘slendr’: (395ms)
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘slendr_0.9.tar.gz’
   
* installing *source* package ‘slendr’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Warning in utils::compareVersion(slim_version, required_version) :
  NAs introduced by coercion
Error: package or namespace load failed for ‘slendr’:
 .onAttach failed in attachNamespace() for 'slendr', details:
  call: if (a[k] > b[k]) return(1) else if (a[k] < b[k]) return(-1L)
  error: missing value where TRUE/FALSE needed
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/slendr’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/v0/h1l93y5d56ndrcl7bg26gysc0000gn/T//RtmpITV464/fileac6936acb8/slendr_0.9.tar.gz’ had non-zero exit status
```

**Comment by bodkan** [comment]
Hello.

The first error looks like an internet problem with a connection to Github. However, it seems that's been resolved now?

As for the second error. I'm investigating now. I will get back to you in a minute... I think I know what's wrong (this comes from a new check for the required SLiM version).

**Comment by jaurbanChicago** [comment]
Ok, I´ll first download the SLiM 3.7.1 and then I will download slendr again! I´ll tell you what happens!

**Comment by jaurbanChicago** [comment]
Yes, I think that is the problem. My internet connection has been unstable today. I´ll wait until it gets better. Thanks again Martin!

**Comment by jaurbanChicago** [comment]
An additional observation Martin, 

Apparently, the map is printing the words "latitude" and "longitude" on the wrong axes of the maps.
![Screen Shot 2022-03-04 at 1 41 10 PM](https://user-images.githubusercontent.com/90297093/156830808-7399097e-a83c-42af-943d-cbee322998da.png)

Best, 

Toño
