### ISSUE TITLE
Generalize the R-tskit interface towards non-slendr tree sequences

### ISSUE THREAD

**Issue by bodkan** [bodkan/slendr#85]
Now that we can load and analyse both SLiM and msprime tree sequences originating from slendr models, it's time to generalize the [`ts_*()` interface](https://www.slendr.net/reference/index.html#tree-sequence-loading-and-processing) so that the users can analyse even non-slendr tree sequences produced by standard non-slendr msprime and SLiM simulations.

This will get us towards slendr that's not just an R-friendly interface for configuring and simulation a specific subset of demographic models in msprime and SLiM, but also a convenient R environment for loading/processing/analyzing/visualizing tskit tree sequences in general.

Especially for spatial models, the benefits having `ts_data()`, `ts_tree()`, `ts_ancestors()`, etc. return proper _sf_ data tables which can be analyzed with the myriad of R packages for geospatial statistics and phylogenetics, would be numerous. People do lots of amazing things with spatial SLiM, for instance, things which slendr is unlikely to support.

---

Part of this effort is to have this generalized interface also compatible with tsinfer and tsdate outputs. Hopefully these are just any other tskit tree sequences. One challenge here will be correctly translating metadata (for now, lat/lon locations and times of nodes). But that should be a solvable problem that I will tackle in a separate issue.

**Comment by bhaller** [comment]
I wonder whether it might make sense to coordinate with @petrelharp to try to make slendr's front end to tree sequences be as similar to pyslim's front end as possible?  Is that a worthwhile goal, or are these really just two completely orthogonal approaches/uses/functionalities?

**Comment by bodkan** [comment]
Hmm, good point. Certainly, there shouldn't be any case where the slendr tskit-R interface would be doing something that would surprise the user who would be familiar with tskit and/or pyslim Python APIs. This is why I have tried to use the same default argument values in all current tskit-R functions of slendr (where applicable).

That said, the interface we have [right now](https://www.slendr.net/reference/index.html#tree-sequence-loading-and-processing) is heavily designed to be R-like. If only because R doesn't really support the kind of OOP style that Python prefers and the way R is often used (being a functional programming language as opposed to primarily OO language) is quite different from a Python approach to data analysis.

In this sense, maybe the R interface actually cannot/shouldn't be that similar. (Again, not talking about what the code does under the hood, but what it "looks like"). Of course, this will be largely a matter of style, but the current admittedly small circle of R users have not complained yet so I hope I've designed the R interface reasonably well (mostly by absorbing the interface styles of my favourite R packages).

More specifically, my first step towards this issue is to take [what we currently have](https://www.slendr.net/reference/index.html#tree-sequence-loading-and-processing) and make two changes:

1. Internal change: make `ts_load()` accept non-slendr tree sequences ("pure" SLiM and msprime, as well as tsinfer outputs), relaxing the expectation that the tree sequence must carry slendr-specific metadata.
2. User-interface change: make sure that all slendr `ts_*()` tskit-R functions properly operate on integer tskit node IDs. This should largely be true already, but there will be instances where this doesn't work at the moment and where "symbolic names" of samples are required (chief among them being simplification which cross-checks information with slendr-specific sample metadata containing symbolic sample names).

**Comment by bhaller** [comment]
I was thinking of, in particular, APIs for accessing metadata on mutations and such; do you plan to provide access at that sort of level?  Anyhow, I hear what you're saying and trust that you will do what is best.  :->

**Comment by bodkan** [comment]
Ah, didn't really get all the way to translating general metadata in my thinking. In general, as far as I know, the metadata seems to be automagically converted to R lists of lists of lists through the [reticulate package](https://rstudio.github.io/reticulate/articles/calling_python.html#lists-tuples-and-dictionaries).

Let's see if some more special treatment would be needed.

Thanks for bringing it up!
